use
	sSQL = sSQL & "This is a piece of text "
	sSQL = sSQL & "This is a piece of text "
	sSQL = sSQL & "This is a parsel of text "
	sSQL = sSQL & "This is a piece of text "
	sSQL = sSQL & "This is another piece of text "
	sSQL = sSQL & "This is a piece of text "
	sSQL = sSQL & "This is a piece of text "
	sSQL = sSQL & "This is an interesting piece of text "
	sSQL = sSQL & "This is a piece of text "
	sSQL = sSQL & "This is a piece of text "
	sSQL = sSQL & "This is a piece of text "
