use
	sSQL = sSQL & "This is a  of text "
	sSQL = sSQL & "This is a  of text "
	sSQL = sSQL & "This is a  of text "
	sSQL = sSQL & "This is something I hate piece of text "
	sSQL = sSQL & "This is a  of text "
	sSQL = sSQL & "This is a  of text "
	sSQL = sSQL & "This is a floop piece of text "
	sSQL = sSQL & "This is a  of text "
	sSQL = sSQL & "This is a  of text "
	sSQL = sSQL & "This is a  of text "
	sSQL = sSQL & "This is a  of text "
